<img src="images/NumPy_logo.png">

This notebook illustrates basic NumPy usage, a key component of the Python scientific computing stack.

In [8]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Numpy is a library that supports multi-dimensional arrays and matrices, as well as high level mathematical operations which are not available in the core Python library.

In [4]:
#Arrays can be created from lists, tuples

In [6]:
#Create a vector
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<type 'numpy.ndarray'>


Arrays are n-dimensional objects.

In [9]:
#Create a 2x2 matrix
y = np.array([[1,2], [3,4]])
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


It is possible to create arrays using a number of different population functions.

####Arange

In [14]:
t = np.arange(100) #The only required argument is stop
print(t)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [15]:
#You can specify start, stop step
t = np.arange(0,1,0.1)
print(t)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]


In [36]:
#For a range of values in a given shape, we can reshape an array
x = np.arange(100).reshape(5,2,-1)  #-1 indicates that we want to explicitly specify all but 1 dimension
print(x)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]

 [[40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]

 [[60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]]

 [[80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


####A brief interlude comparing arrays to lists
Arrays are more flexible than Python lists in some ways, for example the following fails because step is not an integer

In [17]:
from future.utils import lrange
t = lrange(0,1, 0.1)

TypeError: range() integer step argument expected, got float.

Arrays are also more restrictive because the datatype is static (and homogeneous most of the time).

In [19]:
python_list = [1,'foo', 2.0j, {'a':23}]

In [23]:
numpy_array = np.array([1,'foo', 2.0j, {'a':23}])
numpy_array.dtype  #The items are packed but we can not perform any efficient operations.

dtype('O')

####Linspace

In [13]:
t = np.linspace(0,100,10) #Start, stop, n-nodes
print(t)

[   0.           11.11111111   22.22222222   33.33333333   44.44444444
   55.55555556   66.66666667   77.77777778   88.88888889  100.        ]


In [25]:
t = np.logspace(0,100,10, base=np.e)
print(t)

[  1.00000000e+00   6.69104951e+04   4.47701435e+09   2.99559247e+14
   2.00436575e+19   1.34113105e+24   8.97357424e+28   6.00426295e+33
   4.01748207e+38   2.68811714e+43]


####Random

In [27]:
t = np.random.random(10)  #[0.0, 1.0), uniform distribution
print(t)

[ 0.65128251  0.20839844  0.81349081  0.99826022  0.13846316  0.24893748
  0.83937332  0.52853657  0.1241101   0.66352772]


In [30]:
t = np.random.random(size=(3,3))
print(t)
print(t.shape)

[[ 0.47569878  0.21167181  0.40638059]
 [ 0.86584589  0.23330374  0.04844847]
 [ 0.19591028  0.66726191  0.39651521]]
(3, 3)


In [34]:
t = np.random.standard_normal(10) #Mean=0, STD=1
print(t)

[-0.81801088  0.86014563 -0.68356284  0.75712968  0.15342613 -1.25596803
  1.66024559 -1.38393262 -0.01491551 -0.62040366]


####Diagonal

In [38]:
t = np.diag([1,2,3,4])
print(t)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [39]:
#Or chaining calls
t = np.diag(np.arange(1,5))  #Stop is not inclusive
print(t)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


####Eye

In [42]:
t = np.eye(4)
print(t)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


####Zeros and Ones

In [45]:
z = np.zeros((3,3))
o = np.ones((3,3))
print(z)
print()
print(o)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
()
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


###Indexing and Slicing
Frequently, the entirety of a multi-dimensional array is not required.  Just like Python lists, it is possible to access sub-arrays using slicing.

In [52]:
#Create a 5x5 grayscale 'image'
data = np.random.random((5,5))
print(data)

[[ 0.73774361  0.0205892   0.84406223  0.37836267  0.69027188]
 [ 0.72814213  0.95462429  0.41242098  0.96647286  0.87373799]
 [ 0.8120285   0.00259678  0.74174711  0.48829174  0.13351304]
 [ 0.15188112  0.83180929  0.70778027  0.29016796  0.82072328]
 [ 0.98586383  0.77498369  0.07436217  0.76201801  0.32616673]]


In [54]:
#Access a single 'row'
print(data[1])

[ 0.72814213  0.95462429  0.41242098  0.96647286  0.87373799]


In [55]:
#Access a single 'column'
print(data[:,1])

[ 0.0205892   0.95462429  0.00259678  0.83180929  0.77498369]


In [56]:
#Access a single 'pixel'
print(data[0,0])

0.73774361087


In [57]:
#or
print(data[0][0])

0.73774361087


In [58]:
#Access need to be a single row or colum, but can be multiple
print(data[3:]) #4th row onward (0 indexed)

[[ 0.15188112  0.83180929  0.70778027  0.29016796  0.82072328]
 [ 0.98586383  0.77498369  0.07436217  0.76201801  0.32616673]]


In [60]:
print(data[:,-2:]) #4th column onward using reverse indexing

[[ 0.37836267  0.69027188]
 [ 0.96647286  0.87373799]
 [ 0.48829174  0.13351304]
 [ 0.29016796  0.82072328]
 [ 0.76201801  0.32616673]]


In [61]:
#These can be combined
print(data[3:,-2:])

[[ 0.29016796  0.82072328]
 [ 0.76201801  0.32616673]]


####Fancy indexing
Here we will utilize standard indexing and fancy indexing.

In [64]:
#and explicit
print(data[[1,2,4],3:])

[[ 0.96647286  0.87373799]
 [ 0.48829174  0.13351304]
 [ 0.76201801  0.32616673]]


The list `[1,2,4]` can also be stored in a variable

In [65]:
idx = [1,2,4]
print(data[idx,3:])

[[ 0.96647286  0.87373799]
 [ 0.48829174  0.13351304]
 [ 0.76201801  0.32616673]]


Indexing and fancying indexing extend to n-dimensions, just as you would expect it to.  For this section we will use a JPEG Apollo 17 image.

In [25]:
data  = np.random.random((3,5,5))
print(data)

[[[ 0.81649825  0.02995161  0.10082462  0.19697069  0.82211018]
  [ 0.42742297  0.50688864  0.01857562  0.10589608  0.48444024]
  [ 0.53985858  0.72019392  0.11174593  0.11423175  0.09196466]
  [ 0.03404033  0.88822016  0.1729562   0.08964201  0.80938701]
  [ 0.95005861  0.39564868  0.41368477  0.944078    0.05391336]]

 [[ 0.07411987  0.14528633  0.78483345  0.02712182  0.55830497]
  [ 0.43924094  0.05567408  0.24158621  0.19747606  0.30718714]
  [ 0.32813924  0.96370962  0.69418208  0.82924537  0.502479  ]
  [ 0.23377186  0.37603479  0.00695757  0.86287904  0.11527474]
  [ 0.6404687   0.65364601  0.18841309  0.73908529  0.18322738]]

 [[ 0.62478964  0.41673069  0.7109093   0.18966909  0.58800404]
  [ 0.04967404  0.69712321  0.19744441  0.85443252  0.77841484]
  [ 0.02319011  0.07914144  0.96849851  0.40833617  0.88441384]
  [ 0.49960681  0.84597741  0.15682883  0.11156291  0.46593819]
  [ 0.31025696  0.72043174  0.10276895  0.84783057  0.16280479]]]


In [32]:
#In an iPython notebook the print can be omitted....I get tired of typing print
data[:, 2, 2]  #Get the center 'pixel' in all 3 'bands'

array([ 0.11174593,  0.69418208,  0.96849851])

In [33]:
center_box = [1,2,3]
data[:, center_box, center_box]

array([[ 0.50688864,  0.11174593,  0.08964201],
       [ 0.05567408,  0.69418208,  0.86287904],
       [ 0.69712321,  0.96849851,  0.11156291]])

In [34]:
#or programmatically
center_box = np.arange(1,4)
data[:, center_box, center_box]

array([[ 0.50688864,  0.11174593,  0.08964201],
       [ 0.05567408,  0.69418208,  0.86287904],
       [ 0.69712321,  0.96849851,  0.11156291]])

###Masking (Boolean indexing)

In [37]:
data = np.arange(5)
mask = np.array([True, False, True, True, False])
data[mask]

array([0, 2, 3])

####Where

In [42]:
data = np.random.random((3,3,3))
mask = np.where(data < 0.5)
print(mask)

(array([0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 1, 0, 0, 1, 1, 2, 0, 0, 2, 2]), array([2, 0, 1, 1, 2, 0, 1, 1, 1, 2, 0, 1]))


In [43]:
data[mask]

array([ 0.03448906,  0.01448898,  0.45464813,  0.26644401,  0.1202435 ,
        0.41065038,  0.27083748,  0.48241413,  0.10458017,  0.30172972,
        0.10673157,  0.38808592])

In [44]:
mask = np.where((data < 0.25) | (data > 0.75))

In [45]:
data[mask]

array([ 0.03448906,  0.01448898,  0.93832563,  0.1202435 ,  0.76857415,
        0.10458017,  0.89564562,  0.85014542,  0.10673157,  0.80039687])

In [49]:
#Maybe a bit easier to read
mask = (data < 0.25) + (data > 0.75)  #Boolean array plus boolean array is a logical or
mask

array([[[False, False,  True],
        [ True, False, False],
        [ True, False, False]],

       [[False, False,  True],
        [False, False, False],
        [False, False, False]],

       [[ True,  True, False],
        [False,  True,  True],
        [ True, False,  True]]], dtype=bool)

In [48]:
data[mask]

array([ 0.03448906,  0.01448898,  0.93832563,  0.1202435 ,  0.76857415,
        0.10458017,  0.89564562,  0.85014542,  0.10673157,  0.80039687])

###Mathematical operations (Linear Algebra)

In [54]:
a = np.array([[1,2],[3,4]])
b = np.arange(4)
print('a = ', a)
print('b = ', b)

('a = ', array([[1, 2],
       [3, 4]]))
('b = ', array([0, 1, 2, 3]))


In [52]:
b * 2

array([0, 2, 4, 6])

In [53]:
b + 11

array([11, 12, 13, 14])

#### Element-wise operations
By default, mathematical operation are element-wise

In [55]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [56]:
a * b  #Shape mismatch causes element-wise operations to fail

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

By multiplying matrices (vectors) with compatible shapes we can cause background broadcasting to occur.  `c` is broadcast to the same dimensionality as `a` and elementwise multiplication is possible.

In [58]:
c = np.arange(1,3)
a * c

array([[1, 4],
       [3, 8]])

###Matrix multiplication

In [60]:
np.dot(a, c)

array([ 5, 11])

In [61]:
#or
a.dot(c)

array([ 5, 11])

In [65]:
#or cast the arrays to matrices
ma = np.matrix(a)
mc = np.matrix(c).T  #Column and row vectors are distinct
ma * mc

matrix([[ 5],
        [11]])

In [68]:
#Get the inverse
ma.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [71]:
ma.I * ma

matrix([[  1.00000000e+00,   0.00000000e+00],
        [  2.22044605e-16,   1.00000000e+00]])

In [75]:
#Or the determinant
np.linalg.det(ma)

-2.0000000000000004

###Iterating over arrays

In [21]:
data = np.random.randint(0, 10, size=(5,2))
print(data)
for row in data:
    print(row)
    for element in row:
        print(element)

[[4 3]
 [6 2]
 [3 6]
 [2 2]
 [6 6]]
[4 3]
4
3
[6 2]
6
2
[3 6]
3
6
[2 2]
2
2
[6 6]
6
6


In [25]:
#Sometimes it is convenient to have both the value and the index
for i, row in enumerate(data):
    print(i, row)
    for j, element in enumerate(row):
        print(i, j, element)


(0, array([4, 3]))
(0, 0, 4)
(0, 1, 3)
(1, array([6, 2]))
(1, 0, 6)
(1, 1, 2)
(2, array([3, 6]))
(2, 0, 3)
(2, 1, 6)
(3, array([2, 2]))
(3, 0, 2)
(3, 1, 2)
(4, array([6, 6]))
(4, 0, 6)
(4, 1, 6)


### Vectorization
NumPy is most performant when working on matrices and/or vectors, as opposed to elementwise operations. 

The term vectorization refers to the application of some operand to multiple data elements such that the CPU can leverage what is esentially inherent parallelism.

In [6]:
#We have to short circuit the built-in sum call because iPython automatically loads the numpy sum.
from future.utils import lrange
x = lrange(int(1e5))

def pythonsum(x):
    total = 0
    for i in x:
        total += i
    return total

%timeit pythonsum(x)

100 loops, best of 3: 8.09 ms per loop


In [10]:
x = np.arange(1e5, dtype=np.int)
%timeit np.sum(x)

10000 loops, best of 3: 102 µs per loop


This is a simplistic case where a for loop has been replaced with a single SIMD call.  More complex vectorization requires the use of indexing and slicing to avoid for loops.  Checkout [this optimization notebook](http://scipy-lectures.github.io/advanced/optimizing/) for a bit more info if you are interested or chat with me if you have some specific interests.