<img src="images/NumPy_logo.png">

This notebook illustrates basic NumPy usage, a key component of the Python scientific computing stack.

In [1]:
import numpy as np
# or 
# %pylab inline

Numpy is a library that supports multi-dimensional arrays and matrices, as well as high level mathematical operations which are not available in the core Python library.

In [4]:
#Arrays can be created from lists, tuples

In [6]:
#Create a vector
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<type 'numpy.ndarray'>


Arrays are n-dimensional objects.

In [9]:
#Create a 2x2 matrix
y = np.array([[1,2], [3,4]])
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


It is possible to create arrays using a number of different population functions.

####Arange

In [14]:
t = np.arange(100) #The only required argument is stop
print(t)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [15]:
#You can specify start, stop step
t = np.arange(0,1,0.1)
print(t)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]


In [36]:
#For a range of values in a given shape, we can reshape an array
x = np.arange(100).reshape(5,2,-1)  #-1 indicates that we want to explicitly specify all but 1 dimension
print(x)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]

 [[40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]

 [[60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]]

 [[80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


####A brief interlude comparing arrays to lists
Arrays are more flexible than Python lists in some ways, for example the following fails because step is not an integer

In [17]:
from future.utils import lrange
t = lrange(0,1, 0.1)

TypeError: range() integer step argument expected, got float.

Arrays are also more restrictive because the datatype is static (and homogeneous).

In [19]:
python_list = [1,'foo', 2.0j, {'a':23}]

In [23]:
numpy_array = np.array([1,'foo', 2.0j, {'a':23}])
numpy_array.dtype  #The items are packed but we can not perform any efficient operations.

dtype('O')

####Linspace

In [13]:
t = np.linspace(0,100,10) #Start, stop, n-nodes
print(t)

[   0.           11.11111111   22.22222222   33.33333333   44.44444444
   55.55555556   66.66666667   77.77777778   88.88888889  100.        ]


In [25]:
t = np.logspace(0,100,10, base=np.e)
print(t)

[  1.00000000e+00   6.69104951e+04   4.47701435e+09   2.99559247e+14
   2.00436575e+19   1.34113105e+24   8.97357424e+28   6.00426295e+33
   4.01748207e+38   2.68811714e+43]


####Random

In [27]:
t = np.random.random(10)  #[0.0, 1.0), uniform distribution
print(t)

[ 0.65128251  0.20839844  0.81349081  0.99826022  0.13846316  0.24893748
  0.83937332  0.52853657  0.1241101   0.66352772]


In [30]:
t = np.random.random(size=(3,3))
print(t)
print(t.shape)

[[ 0.47569878  0.21167181  0.40638059]
 [ 0.86584589  0.23330374  0.04844847]
 [ 0.19591028  0.66726191  0.39651521]]
(3, 3)


In [34]:
t = np.random.standard_normal(10) #Mean=0, STD=1
print(t)

[-0.81801088  0.86014563 -0.68356284  0.75712968  0.15342613 -1.25596803
  1.66024559 -1.38393262 -0.01491551 -0.62040366]


####Diagonal

In [38]:
t = np.diag([1,2,3,4])
print(t)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [39]:
#Or chaining calls
t = np.diag(np.arange(1,5))  #Stop is not inclusive
print(t)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


####Eye

In [42]:
t = np.eye(4)
print(t)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


####Zeros and Ones

In [45]:
z = np.zeros((3,3))
o = np.ones((3,3))
print(z)
print()
print(o)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
()
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
